version: '3.8'

services:

  web:
    build:
      context: ./registro 
      dockerfile: Dockerfile 
    container_name: project
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./registro:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:12
    
    environment:
      - POSTGRES_DB=registration_db
      - POSTGRES_USER=registration_user
      - POSTGRES_PASSWORD=registration_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend


volumes:
  db_data:

networks:
  backend:
