version: '3.8'

services:
  web:
    image: python:3.9
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./registration:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
    networks:
      - backend

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=registration_db
      - POSTGRES_USER=registration_user
      - POSTGRES_PASSWORD=registration_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
